solve 02-components
js-tasks-ru/vue-20231109_velibegov pull request #4
Opened 2023-10-30 19:31 UTC by velibegov

2023-10-30 19:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-31 23:44 UTC, ShGKme requested changes
В последней задаче выводится фиксированный текст ошибки из теста, но не полученная ошибка.

2023-10-31 23:44 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click="this.incrementCounter">{{ this.count }}</button>`,
`this` в шаблоне не используют, код в шаблоне уже исполняется со всеми свойствами экземпляра в области видимости

2023-10-31 23:44 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +        this.error = 'Test Error';
`'Test Error'` - это не полученная ошибка, а текст ошибки из соответствующего теста... 

Настоящий текст ошибки можно достать из исключения, которое выбрасывает функция `fetchMeetupById`. Сообщение ошибки можно получить из свойства `error.message` у JS ошибки: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message

2023-10-31 23:44 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +      }
Роль блока `finally` - это не выполнить что-то "после" `try/catch`, а гарантированно выполнить какой-то код, даже если `try/catch` завершился, например, с `return`. Обычно это только очищение и освобождение ресурсов, которые были выделены в блоке `try/catch`.

Если нужно выполнить какой-то код после `try/catch`, то это можно сделать непосредственно просто следующей строчкой, например

```js
try {
  this.meetup = null;
  this.meetup = await fetchMeetupById(this.meetupId);
} catch (error) {
  this.error = 'Test Error';
}
this.loading = false; // Эта строка гарантирована будет выполнена как обычная строка кода
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

> It is generally a bad idea to have control flow statements in the finally block. Only use it for cleanup code.

2023-10-31 23:44 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +    </UiContainer>
Эти два контейнера выводятся всегда, даже если ни загрузки, ни ошибки уже нет

2023-10-31 23:44 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +  },
Все эти методы делают вычисления, зависящие только от состояния компонента. Лучше их явно описывать как вычисляемые свойства.

Так компонент будет проще отлаживать (их значение видно в vue-devtools).

И так не будет вызова методов в шаблоне, что в общем случае скорее плохая практика, кроме простых утилит и форматирования. Шаблон лучше держать декларативным, описывающим результат, а императивным — с вычислением результата. В то же время, при наличии вызова методов в шаблоне нужно дополнительно проверять, что эти методы производительные и не имеют побочных эффектов.

2023-11-01 15:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-01 15:11 UTC, velibegov commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button type="button" @click="this.incrementCounter">{{ this.count }}</button>`,
fixed

2023-11-01 15:11 UTC, velibegov commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +  },
fixed

2023-11-01 15:11 UTC, velibegov commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +        this.error = 'Test Error';
fixed

2023-11-01 15:11 UTC, velibegov commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +      }
fixed

2023-11-01 15:11 UTC, velibegov commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +    </UiContainer>
fixed

2023-11-01 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-01 16:42 UTC, ShGKme requested changes

2023-11-01 16:42 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <p class="agenda-item__talk" v-show="isTalkType">
Пропустил это на прошлом ревью. Здесь должна использоваться директива `v-if`.

`v-show` - это директива "отображения". Она используется, чтобы показать или скрыть от пользователя существующий контент. Например, в UI элементах, где выводится список вариантов.

`v-if` - директива ветвления, когда есть разные сценарии рендеринга и какой-то блок может быть нужен в рендеринге или вообще не будет рендериться.

При использовании `v-show` здесь всегда рендерится блок с данными только для доклада, в которой при этом пустые значения. А при изменении данных могут быть и ошибки, так как разработчик может не ожидать, например, что будет работа с языком или докладчиком у кофе брейка.

2023-11-01 18:12 UTC, velibegov commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +    icon: function() {
fixed

2023-11-01 18:12 UTC, velibegov commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <p class="agenda-item__talk" v-show="isTalkType">
fixed

2023-11-01 18:14 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-02 01:38 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-11-02 16:54 UTC, velibegov commented
-

2023-11-03 13:23 UTC, ShGKme approved these changes

2023-11-03 13:25 UTC, merged

2023-11-03 13:59 UTC, ShGKme commented
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

Была проблема на CI, не обработался запрос на автоматический мерж