04-vue-cli решение заданий
js-tasks-ru/vue-20231109_velibegov pull request #6
Opened 2023-12-02 09:22 UTC by velibegov

2023-12-02 09:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-17 15:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-20 02:05 UTC, ShGKme requested changes

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToastList.vue
> +    <slot name="default"></slot>
Имя слота `default` можно не указывать, это имя по умолчанию

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      </template>
Элемент `<template>` в шаблоне нужен, когда требуется для директив `v-if` или `v-for` обернуть несколько узлов сразу.

Если узел один, то директиву можно использовать непосредственно на нём без лишних обёрток.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      };
Здесь из данных компонента передаётся класс и иконка в тост. Получается не очень удобный интерфейс компонента `UiToast`. Пользователь компонента должен знать, какое название иконки передавать и какое название класса (из внутренней реализации компонента) требуется передать для тоста каждого типа.

Это неудобно и может привести к тому, что в разных местах приложения одинаковые тосты будут иметь разный стиль или иконки при использовании компонента `UiToast`

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Так уделять тосты некорректно. Действие `toast.showToast = false` через `v-if` скрывает тост из DOM. Но сам тост остаётся в памяти приложения, включая экземпляр Vue компонента `UiToast`. В итоге, чем дольше работает приложение и чем больше тостов в нём показалось, тем больше памяти занимают висящие в памяти экземпляры этого компонента. И все они будут ре-рендериться при добавлении нового тоста (хотя и не будут менять DOM). Это утечка памяти.

При скрытии тоста он должен полностью пропадать, включая его компонент.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      };
Лучше передавать тип тоста, а уже в `UiToast` определять, какой свой класс и иконку он будет испоьлзовать для вывода тоста каждого типа.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      },
`basicOptions` используется просто как константа и не является состоянием компонента. Его можно описать в обычной переменной, не добавляя в реактивные данные экземпляра компонента.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
Обычно параметры удобнее передавать отдельно, не оборачивая их в ещё один объект. Параметры (пропсы) фактически уже объект ($props).

Передача отдельных параметров удобнее пользователю компонента: видны отдельные параметры и их типы без дополнительной документации и TypeScript, не нужно обязательно оборачивать в объект.

```html
<UiToast :toast="{ icon: 'error', message: 'error' }" />

<UiToast icon="error" message="error" />
```

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  emits: ['hide-toast'],
Описывать и порождать события, как и параметры, принято в `camelCase`. В `kebab-case` они только используются в шаблоне из-за HTML синтаксиса.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
Также в имена параметров и событий обычно не добавляют имя компонента. Пользователь компонента, подписываясь на событие у `UiToast` уже знает, что событие `hide` будет именно событием тоста, без уточнений `hideToast`

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +      this.$emit("hide-toast", this.toast);
С событием не нужно отдавать `this.toast`. Его родитель итак знает, у какого тоста порождается событие `hide-toast`. Он знает этот `toast`, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас `toast` просто получается от родителя и отправляется ему же обратно.

При этом не может возникнуть ситуации, когда один тост (`UiToast`) будет сообщать об удалении какого-то другого тоста. Лучше не передавать лишних данных в событиях

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      </template>
Здесь `TheToaster` даже не использует полученный тост с событием `hide-toast`, так как он уже доступен в переменной `toast`

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      <span>{{ getOption()?.text ?? title }}</span>
Здесь и в других местах компонента в шаблоне вызываются методы. Вызывать методы в шаблоне без необходимости в целом плохая практика. Это делает шаблон менее декларативным, так как в нём больше не описано какое значение выводится или используется, а описано как вычислить это значение. В то же время это увеличивает временную сложность. Чуть ниже циклом выводятся кнопки, и при выводе каждой кнопки заново вызывается метод который циклом перебирает все элементы массива для вычисления одного и того же значения. Получается квадратичная сложность при каждом выводе, которая в лучшем случае могла быть `O(1)`, так как наличие `dropdown__item_icon`, например, не поменяется если не изменится список вариантов.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Здесь хорошо подойдёт метод `some`.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
И метод `hasIcon`, и `getOption` - только вычисляют значение на основе состояния компонента. Они могут быть заменены на вычисляемое свойство, чтобы вычислять эти значения, только когда изменяются зависимости вычисления и значение может получиться новым.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +           v-for="(day, index) in getMonthData()" :key="index" tabindex="0">
Аналогично по поводу вызова методов в шаблоне.

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Только в методе `getNextMonth` предусмотрено, что текущий день может не существовать в следующем месяце. Но `getPreviousMonth` это не учитывает, и переключение назад может не работать, например, при переходе с 31 марта на февраль (будет переход на 31 февраля).

2023-12-20 02:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Проверка в методе получилась довольно сложной. Всё упрощается, если в качестве текущей даты или хотя бы даты при переключении использовать не текущий день (от 1 до 31), а такой, который есть в любом месяце, например, 1 или 15. Тогда не будет простое переключение месяца будет всегда корректным.

2023-12-20 02:05 UTC, ShGKme commented on 05-vue-router/01-AuthPages/App.vue
> +  }
При таком решении здесь может выводиться только компоненты `PageIndex`, `PageLogin` и `PageRegister`. Добавление в приложение новых маршрутов потребует изменения этого компонента и добавления здесь новых ифов. При этом в описании роутера уже задано, каким компонентом должен выводиться какой маршрут, и здесь эта информация продублирована. Изменение описания маршрута в конфигурации роутера не повлияет не изменение вывода в этом месте.

За вывод компонента текущего маршрута отвечает компонент `<RouterView>`, который будет выводить именно компонент из описания текущего маршрута самостоятельно.

2023-12-20 02:05 UTC, ShGKme commented on 05-vue-router/01-AuthPages/components/MeetupsLogo.vue
> +    <router-link to="/" class="nav__link">
Здесь изменился класс элемента.

2023-12-20 02:05 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +      const fromRoute = this.$router.currentRoute.value.query.from;
Текущий маршрут можно получить из специального свойства `this.$route` вместо `this.$router.currentRoute.value`

2023-12-20 02:05 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +    ) {
Перебирать все `matched` для проверки `meta` свойств было нужно только в Vue 2. Но в Vue 3 мета свойства наследуются дочерними маршрутами и можно напрямую работать с `to.meta` без перебора всех маршрутов.

2023-12-20 02:05 UTC, ShGKme commented on 05-vue-router/05-AuthGuard/router/index.js
> +});
Вариант с использованием коллбека `next` работает в Vue Router 4, но это устаревший вариант из Vue 2.

В актуальном роутере можно просто возвращать значение как напрямую `return`-ом так и через промис.

https://router.vuejs.org/guide/advanced/navigation-guards.html#Navigation-Guards

> Optional third argument `next`
> 
> 
> In previous versions of Vue Router, it was also possible to use a *third argument* `next`, this was a common source of mistakes and went through an [[RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0037-router-return-guards.md#motivation)](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0037-router-return-guards.md#motivation) to remove it.
>

2025-07-07 15:57 UTC, closed without merging